/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.medecin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Archive;
import model.ConnexionBD;
import ui.AboutPageUi;
import ui.HeisView;
import ui.ListePUi;
import ui.MedecinDashboardUi;
import static ui.MedecinDashboardUi.url;
import ui.ProfilMedecin;
import ui.QuestionArchiveUi;
//import ui.QuestionUi;

/**
 *
 * @author pak
 */
public class ListArchive extends javax.swing.JFrame {
    JTable table1;
       JTable table2;
       int id;
        Connection con=null;
        ConnexionBD cobd=new ConnexionBD();
        PreparedStatement pat=null;
        ResultSet rs=null;
         ResultSet rs0=null;
//       Connection con=null;
    /**
     * Creates new form ListArchive
     */
    public ListArchive() {
        initComponents();
this.id=1;
pan1.setVisible(false);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        profil = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        recherche = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pel = new javax.swing.JPanel();
        nel = new javax.swing.JScrollPane();
        pan1 = new javax.swing.JScrollPane();
        getselectdrow = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user123.PNG"))); // NOI18N
        jPanel2.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 115));

        jButton8.setBackground(new java.awt.Color(0,0,0,0));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_left_48px.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 50, 50));

        jPanel1.setBackground(new java.awt.Color(255, 249, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 204));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round_48px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 180));

        email.setBackground(new java.awt.Color(51, 51, 255));
        email.setForeground(new java.awt.Color(0, 0, 255));
        email.setText("jLabel6");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        ip.setBackground(new java.awt.Color(0, 0, 255));
        ip.setForeground(new java.awt.Color(51, 51, 255));
        ip.setText("jLabel8");
        jPanel2.add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 70, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Acceuil");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list_16px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 40, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Liste Patient");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_to_clipboard_24px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nouvelle consultation");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 350, 130, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archive_folder_24px.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 40, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Parametre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 440, 70, -1));

        jButton9.setBackground(new java.awt.Color(51, 51, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_settings_male_16px.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 40, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Archives");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 390, 70, -1));

        email1.setText("jLabel22");
        jPanel2.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 60, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 590));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recherche.setBackground(new java.awt.Color(204, 204, 255));
        recherche.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        recherche.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 160, 20));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_16px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 40, 20));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_26px.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 40, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_arrow_24px.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 820, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Liste des archives");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 820, 50));

        pel.setBackground(new java.awt.Color(240, 255, 255));
        pel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1=new Archive().listArchive();
        nel.setViewportView(table1);
        nel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nelMouseClicked(evt);
            }
        });
        pel.add(nel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 680, 130));

        table2=new Archive().listArchiveId(this.getId());
        pan1.setViewportView(table2);
        pan1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pel.add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 700, 150));

        getselectdrow.setBackground(new java.awt.Color(153, 153, 255));
        getselectdrow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getselectdrow.setText("Obtenir les differents resultats de L'archive");
        getselectdrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getselectdrowActionPerformed(evt);
            }
        });
        pel.add(getselectdrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 320, 30));

        text.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pel.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 710, 30));

        getContentPane().add(pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 710, 380));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dash.PNG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 740, 450));

        setSize(new java.awt.Dimension(933, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        new QuestionUi().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new AboutPageUi().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        new MedecinDashboardUi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nelMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel model= (DefaultTableModel)table1.getModel();
//        int selectrow = table1.getSelectedRow();
//        //jTextId.setText(model.getValueAt(selectrow, 0).toString());
//          id = (int) model.getValueAt(selectrow, 0);
//        listeExamen.setVisible(true);
//        pel.setVisible(false);
               try{
                   int selectrow = table1.getSelectedRow(); 
                    this.setId((int)(table1.getModel().getValueAt(selectrow,0 )));
//                    id = (int) model.getValueAt(selectrow, 0);

               //pan1.
               } catch(Exception e){
                   System.out.println("Erreur ");
               }
    }//GEN-LAST:event_nelMouseClicked

    private void getselectdrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getselectdrowActionPerformed
//  try{
//                                                                                                   
//                   int selectrow = table1.getSelectedRow(); 
//                   int id=(int)(table1.getModel().getValueAt(selectrow,0 ));
////                    id = (int) model.getValueAt(selectrow, 0);
//                 table2=new Archive().listArchiveId(id);
//                 pan1.setViewportView(table2); 
//                 pel.setVisible(false);
//                 
//               } catch(Exception e){
//                   System.out.println("Erreur ");
//               }
//Integer.parseInt(cniclient.getText())
                   int selectrow = table1.getSelectedRow(); 
                    ip.setText((table1.getModel().getValueAt(selectrow,0 )).toString());
                  text.setText("Résultats de l'archive "+(table1.getModel().getValueAt(selectrow,1 )).toString());
                    this.setId(Integer.parseInt(ip.getText()));
//                    id = (int) model.getValueAt(selectrow, 0);
                        table2=new Archive().listArchiveId(this.getId());
                        pan1.setViewportView(table2);
               pan1.setVisible(true);
              
//        TableModel model=table1.getModel();
//        int index = table1.getSelectedRows();
////        int index[] = table1.getSelectedRows();
//        Object[] row=new Object[4];
////        table t=new table ();
//         DefaultTableModel model1= (DefaultTableModel)t.jTable1.getModel();
////        for(int i =0; i<index; i++){
////        row[0]= model.getValueAt(index[i], 0);
////        row[1]= model.getValueAt(index[i], 0);
////        row[2]= model.getValueAt(index[i], 0);
////        row[3]= model.getValueAt(index[i], 0);
//        //row[0]= model1.getValueAt(index[i], 0);
//        
////        model1.addRow(row);
//        
////    }
////        t.setVisible(true);
    }//GEN-LAST:event_getselectdrowActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       DefaultTableModel tab;
       tab = (DefaultTableModel)table1.getModel();
        String search =recherche.getText().toLowerCase();
        TableRowSorter<DefaultTableModel>  az =new TableRowSorter<DefaultTableModel>(tab);
        table1.setRowSorter(az);
        az.setRowFilter(RowFilter.regexFilter(search));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ListePUi().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HeisView h=  new HeisView();
        h.email.setText(this.email.getText());
        h.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new QuestionArchiveUi().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String sql ="SELECT  `nomMedecin`, `prenomMedecin`, `service`, `telMedecin`, `emailMedecin`, `password`, `urlImage`, `sexeM` FROM `medecin` WHERE `emailMedecin` ='"+this.email.getText()+"' ";
        cobd= new ConnexionBD();
        try {
            ResultSet rs=cobd.requeste(sql);
            if(rs.next()){
                ImageIcon ii=new ImageIcon(url.getText());
                ProfilMedecin pro= new ProfilMedecin();
                pro.email.setText(rs.getString("emailMedecin"));
                pro.image.setIcon(ii);
                pro.profil.setIcon(ii);
                pro.nomMedecin.setText(rs.getString("nomMedecin"));
                pro.prenomMedecin.setText(rs.getString("prenomMedecin"));
                pro.service.setSelectedItem(rs.getString("service"));
                pro.telMedecin.setValue(rs.getString("telMedecin"));
                pro.emailMedecin.setText(rs.getString("emailMedecin"));
                pro.password.setText(rs.getString("password"));
                pro.sexeM.setSelectedItem(rs.getString("sexeM"));
                pro.name.setText(name.getText());
                pro.setVisible(true);
                this.setVisible(false);
            }else{

            }
        } catch (SQLException ex) {
            Logger.getLogger(MedecinDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MedecinDashboardUi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              ListArchive a=  new ListArchive();
                a.setVisible(true);
                  
        //pel.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JButton getselectdrow;
    private javax.swing.JLabel ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static final javax.swing.JLabel name = new javax.swing.JLabel();
    private javax.swing.JScrollPane nel;
    private javax.swing.JScrollPane pan1;
    private javax.swing.JPanel pel;
    private javax.swing.JLabel profil;
    private javax.swing.JTextField recherche;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables

  
}
