/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.ConnexionBD;
import model.Discussion;
import model.Patient;

/**
 *
 * @author pak
 */
public class PatientDashboardUi extends javax.swing.JFrame {
   
    JTable table1;
    ConnexionUi con=new ConnexionUi();
    ConnexionBD conbd;
      PreparedStatement patp=null;
      int ip;
      int idm=21, idp=13;
    /**
     * Creates new form PatientDashboardUi
     */
    public PatientDashboardUi() {
        initComponents();
         paneldossierP.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
         chat.setVisible(false);
        accueil.setVisible(true);
        question.setVisible(false);
       // this.setIp(Integer.parseInt(id.getText()));
    }

    public int getIp() {
        return ip;
    }

    public void setIp(int ip) {
        this.ip = ip;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        chat = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        accueil = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        question = new com.k33ptoo.components.KGradientPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        paneldossierP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_left_16px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 30, 20));

        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 204));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round_48px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 50));

        profil.setBackground(new java.awt.Color(51, 51, 255));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_profile_80px.png"))); // NOI18N
        profil.setBorder(null);
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });
        jPanel1.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 80));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("jLabel1");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 80, 20));

        jButton2.setBackground(new java.awt.Color(240, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/moleskine_26px.png"))); // NOI18N
        jButton2.setText("Mon dossier");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 253, 140, 40));

        jButton3.setBackground(new java.awt.Color(240, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/speech_bubble_26px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 60, 40));

        jButton4.setBackground(new java.awt.Color(240, 252, 244));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_24px.png"))); // NOI18N
        jButton4.setText("Accueil     ");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 450));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(102, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_26px.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 31, 40, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel8.setText("Non lus");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 20, 20));

        jButton6.setBackground(new java.awt.Color(102, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/round_30px.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 255)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 37, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 630, 70));

        chat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(97, 142, 116));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 42, 3));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Discussion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        chat.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 590, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        chat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 77, 590, 213));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");
        chat.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 410, 32));

        jButton5.setBackground(new java.awt.Color(240, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper_plane_26px.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        chat.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 55, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("A :");
        chat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 307, 24, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextField2.setText("ex: exemple@gmail.com");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        chat.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 304, 221, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Corps du message:");
        chat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 116, -1));

        jButton8.setBackground(new java.awt.Color(240, 252, 252));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButton8.setBorder(null);
        chat.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 40, 30));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField3.setText("jTextField3");
        chat.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 301, 190, 31));

        jButton9.setBackground(new java.awt.Color(240, 252, 252));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_26px.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        chat.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 40, 30));

        getContentPane().add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 630, 380));

        jPanel4.setBackground(new java.awt.Color(168, 209, 222));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Accueil");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout accueilLayout = new javax.swing.GroupLayout(accueil);
        accueil.setLayout(accueilLayout);
        accueilLayout.setHorizontalGroup(
            accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accueilLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        accueilLayout.setVerticalGroup(
            accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getContentPane().add(accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 630, 380));

        question.setBackground(new java.awt.Color(204, 204, 255));
        question.setkStartColor(new java.awt.Color(153, 153, 255));

        jLabel10.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Voulez-vous vraiment vous déconnecter ?");

        jButton10.setBackground(new java.awt.Color(0, 204, 0));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("OUI");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 51, 51));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("NON");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jButton10))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(jButton11))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel11)
                            .addGap(20, 20, 20)
                            .addComponent(jButton10))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jButton11))
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout questionLayout = new javax.swing.GroupLayout(question);
        question.setLayout(questionLayout);
        questionLayout.setHorizontalGroup(
            questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        questionLayout.setVerticalGroup(
            questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 510, 230));

        javax.swing.GroupLayout paneldossierPLayout = new javax.swing.GroupLayout(paneldossierP);
        paneldossierP.setLayout(paneldossierPLayout);
        paneldossierPLayout.setHorizontalGroup(
            paneldossierPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldossierPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panedossierP, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneldossierPLayout.setVerticalGroup(
            paneldossierPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panedossierP, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        getContentPane().add(paneldossierP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 630, 310));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MON DOSSIER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 74, 630, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel1.setText("Ici on vous présente les differents examen que vous avez effectuez !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 320, 20));

        setSize(new java.awt.Dimension(748, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new AboutPageUi().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        new QuestionUi().setVisible(true);
//        this.setVisible(false);
  paneldossierP.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
         chat.setVisible(false);
        accueil.setVisible(false);
        question.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed
String sql="SELECT `idPatient`, `nomPatient`, `prenomPatient`, `dateNaissance`, `sexeP`, `telPatient`, `profession`, `mailPatient`, `urlImage` FROM `patient` WHERE `mailPatient`='"+email.getText()+"'";
        // TODO add your handling code here:
        conbd=new ConnexionBD();
        try {
            ResultSet rs=conbd.requeste(sql);
            if(rs.next()){
                  EditPatientInfoUi ed=new EditPatientInfoUi();
        ed.name.setText(name.getText());
        ed.nomPatient.setText(rs.getString("nomPatient"));
        ed.prenomPatient.setText("prenomPatient");
        ed.dateNaissance.setText("dateNaissance");
        ed.sexe.setSelectedItem("sexeP");
        ed.profession.setSelectedItem("profession");
        ed.mailPatient.setText("mailPatient");
//        ed.mailPatient.setText("mailPatient");
        ed.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PatientDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_profilActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         paneldossierP.setVisible(false);
          question.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        accueil.setVisible(false);
        jTextField3.setVisible(false);
        jButton8.setVisible(false);
         jTextField1.setVisible(true);
         jTextField2.setVisible(true);
         jButton5.setVisible(true);
         jLabel4.setVisible(true);
         jLabel6.setVisible(true);
        chat.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        paneldossierP.setVisible(false);
        question.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
         chat.setVisible(false);
        accueil.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          accueil.setVisible(false);
          question.setVisible(false);
          paneldossierP.setVisible(true);
           chat.setVisible(false);
         jLabel1.setVisible(true);
         jLabel3.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         paneldossierP.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        accueil.setVisible(false);
        jTextField3.setVisible(true);
        jButton8.setVisible(true);
         jTextField1.setVisible(false);
         jTextField2.setVisible(false);
         jButton5.setVisible(false);
         jLabel4.setVisible(false);
         jLabel6.setVisible(false);
        chat.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql1="SELECT * FROM `patient` WHERE mailPatient='"+email.getText()+"'";
        String sql2="SELECT * FROM `medecin` WHERE emailMedecin='"+jTextField2.getText()+"' ";
        conbd=new ConnexionBD();
        
        try {
            String mail2 = null,mail1=null;
            
                    ResultSet r1=conbd.requeste(sql1);
             ResultSet r2=conbd.requeste(sql2);
             if(r1.next()){
                 idp=Integer.parseInt(r1.getString("idPatient"));
                  mail1=r1.getString("mailPatient");
             }
             if(r2.next()){
                 idm=Integer.parseInt(r2.getString("idMedecin"));
                   mail2=r2.getString("emailMedecin");
             }
             Discussion discos=new Discussion(idp, idm, jTextField1.getText());
             boolean ok=discos.createDiscos();
             if(ok){
                 JOptionPane.showMessageDialog(null, "Message envoyé avec succes "+mail2+" !");
                 /**
                  * debut affichage
                  */
                 String sql="SELECT * FROM `conversation` WHERE `idMedecin`="+idm+" AND `idPatient`="+idp+"";
                    ResultSet rs;
                    String text="";
                    String ras="rien";
                try {
                    rs = conbd.requeste(sql);
                     while(rs.next()){
                       if(!(rs.getString("msg_patient").contentEquals(ras.toString()))){
                            if( !(rs.getString("msg_medecin").contentEquals(ras.toString()))){
                                 text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                        
                            }else if(rs.getString("msg_medecin").contentEquals(ras.toString())){
                                 //text=text+"\nPatient: "+rs.getString("msg_patient")+"\nLe "+rs.getString("heurePatient")+"\n";  
                            text=text+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                         }
                        }else if(!(rs.getString("msg_medecin").contentEquals(ras.toString()))){
                            if(!(rs.getString("msg_patient").contentEquals(ras.toString()))){
                                 //text=text+"\nPatient: "+rs.getString("msg_patient")+"\nLe "+rs.getString("heurePatient")+"\n                                                                         Medecin: "+rs.getString("msg_medecin")+"\n                                                                         Le"+rs.getString("heureMedecin")+"\n";  
                         text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                        
                            }else if(rs.getString("msg_patient").contentEquals(ras.toString())){
                                 text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n";  
                        // text=text+"\n                                                                         Medecin: "+rs.getString("msg_medecin")+"\n                                                                         Le "+rs.getString("heureMedecin")+"\n";  
                          }
                        }else{
                            text=text+"\n";
                        }
                    }
                    jTextArea1.setText(text);
                } catch (SQLException ex) {
                    Logger.getLogger(PatientDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                    
                        
                 //fin
      
             }else{
                  JOptionPane.showMessageDialog(null, "Message non envoyé  "+mail2+" ! \n Ondirait que ce dernier est introuvable, veuillez entrez une adresse mail valide .");
             }
        } catch (SQLException ex) {
            Logger.getLogger(PatientDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
              String sql1="SELECT * FROM `patient` WHERE mailPatient='"+email.getText()+"'";
        String sql2="SELECT * FROM `medecin` WHERE emailMedecin='"+jTextField2.getText()+"' ";
        conbd=new ConnexionBD();
        int idm=21, idp=13;
        try {
            String mail2 = null,mail1=null;
            
                    ResultSet r1=conbd.requeste(sql1);
             ResultSet r2=conbd.requeste(sql2);
             if(r1.next()){
                 idp=Integer.parseInt(r1.getString("idPatient"));
                  mail1=r1.getString("mailPatient");
             }
             if(r2.next()){
                 idm=Integer.parseInt(r2.getString("idMedecin"));
                   mail2=r2.getString("emailMedecin");
             }
           
                 /**
                  * debut affichage
                  */
                 String sql="SELECT * FROM `conversation` WHERE `idMedecin`="+idm+" AND `idPatient`="+idp+"";
                    ResultSet rs;
                    String text="";
                    String ras="rien";
                try {
                    rs = conbd.requeste(sql);
                    while(rs.next()){
                       if(!(rs.getString("msg_patient").contentEquals(ras.toString()))){
                            if( !(rs.getString("msg_medecin").contentEquals(ras.toString()))){
                                 text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                        
                            }else if(rs.getString("msg_medecin").contentEquals(ras.toString())){
                                 //text=text+"\nPatient: "+rs.getString("msg_patient")+"\nLe "+rs.getString("heurePatient")+"\n";  
                            text=text+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                         }
                        }else if(!(rs.getString("msg_medecin").contentEquals(ras.toString()))){
                            if(!(rs.getString("msg_patient").contentEquals(ras.toString()))){
                                 //text=text+"\nPatient: "+rs.getString("msg_patient")+"\nLe "+rs.getString("heurePatient")+"\n                                                                         Medecin: "+rs.getString("msg_medecin")+"\n                                                                         Le"+rs.getString("heureMedecin")+"\n";  
                         text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n                                                                        Vous: "+rs.getString("msg_patient")+"\n                                                                         Le "+rs.getString("heurePatient")+"\n";  
                        
                            }else if(rs.getString("msg_patient").contentEquals(ras.toString())){
                                 text=text+"\n"+mail2+": "+rs.getString("msg_medecin")+"\nLe "+rs.getString("heureMedecin")+"\n";  
                        // text=text+"\n                                                                         Medecin: "+rs.getString("msg_medecin")+"\n                                                                         Le "+rs.getString("heureMedecin")+"\n";  
                          }
                        }else{
                            text=text+"\n";
                        }
                    }
                    jTextArea1.setText(text);
                } catch (SQLException ex) {
                    Logger.getLogger(PatientDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                    
                        
                 //fin
      
            
        } catch (SQLException ex) {
            Logger.getLogger(PatientDashboardUi.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new ConnexionUi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        paneldossierP.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
         chat.setVisible(false);
        accueil.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboardUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accueil;
    private javax.swing.JPanel chat;
    public static final javax.swing.JLabel email = new javax.swing.JLabel();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public static final javax.swing.JLabel name = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane panedossierP = new javax.swing.JScrollPane();
    private javax.swing.JPanel paneldossierP;
    public static final javax.swing.JButton profil = new javax.swing.JButton();
    private com.k33ptoo.components.KGradientPanel question;
    // End of variables declaration//GEN-END:variables
}
