/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Medecin;

/**
 *
 * @author pak
 */
public class RegisterMedecin extends javax.swing.JFrame {

    /*
     * Creates new form ProfilPatient
     */
    public RegisterMedecin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nomMedecin = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        urlImageM = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prenomMedecin = new javax.swing.JTextField();
        service = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        emailMedecin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sexeM = new javax.swing.JComboBox<>();
        telMedecin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomMedecin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nomMedecin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nomMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomMedecinActionPerformed(evt);
            }
        });
        jPanel1.add(nomMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 183, -1));

        urlImageM.setEditable(false);
        jScrollPane2.setViewportView(urlImageM);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Image:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, -1));

        jButton1.setBackground(new java.awt.Color(240, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Pacourir...");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("NOM:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("PRENOM:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("SEXE:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 41, 23));

        prenomMedecin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prenomMedecin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(prenomMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 183, -1));

        service.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        service.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imagerie", "Radio", "Scanner", "Analyse", " " }));
        service.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        jPanel1.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 170, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Service");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("mot de passe ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 20));

        password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 170, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("E-mail :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        emailMedecin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailMedecin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(emailMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 170, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("TEL:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 30, 20));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 130));

        jButton4.setBackground(new java.awt.Color(127, 222, 52));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("S'enregister");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        sexeM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sexeM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        jPanel1.add(sexeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, -1));

        telMedecin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(telMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 170, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 650, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilPatient.PNG"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 840, 310));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 310));

        setSize(new java.awt.Dimension(851, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMedecinActionPerformed

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

           Medecin foto=new Medecin(nomMedecin.getText(), prenomMedecin.getText(), service.getSelectedItem().toString(), (int)telMedecin.getValue(), emailMedecin.getText(),password.getText(),urlImageM.getText(),sexeM.getSelectedItem().toString());
        boolean ok=foto.saveMedecin();
        if(ok==true){
            JOptionPane.showMessageDialog(null, "Enregistrement du médecin "+nomMedecin.getText()+" "+prenomMedecin.getText()+" effectuer avec succes ");
        MedecinDashboardUi p= new MedecinDashboardUi();
         ImageIcon Ii=new ImageIcon(urlImageM.getText());
                String n=nomMedecin.getText().toUpperCase();
                String P=prenomMedecin.getText().toUpperCase();
                p.name.setText((n.charAt(0))+""+P.charAt(0));
                p.mail.setText(emailMedecin.getText());
                p.url.setText(urlImageM.getText());
                if(this.urlImageM.getText()==null){
                     ImageIcon Ii1=new ImageIcon("C:\\Users\\pak\\Documents\\NetBeansProjects\\Main_Projet_Of_Gestion_des_Imageries_POO\\src\\images\\user123.PNG");
                   p.statut.setIcon(Ii1);
                }else{
                     p.statut.setIcon(Ii);
                }
               
                p.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Erreur de l'enregistrement du médecin "+nomMedecin.getText()+" "+nomMedecin.getText());
      

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ConnexionUi().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           JFileChooser brose= new JFileChooser();
        //extension
        FileNameExtensionFilter ext=new FileNameExtensionFilter("png", "jpg","jpeg");
        brose.addChoosableFileFilter(ext);
       int showopen= brose.showOpenDialog(null);
       if(showopen ==JFileChooser.APPROVE_OPTION ){
       File selectfile=  brose.getSelectedFile();
       String path= selectfile.getAbsolutePath();
       JOptionPane.showMessageDialog(null, selectfile);
       urlImageM.setText(path);
//       display image in jlabel
  
           ImageIcon Ii=new ImageIcon(path);
           image.setIcon(Ii);
    }              
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterMedecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailMedecin;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomMedecin;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField prenomMedecin;
    private javax.swing.JComboBox<String> service;
    private javax.swing.JComboBox<String> sexeM;
    private javax.swing.JSpinner telMedecin;
    private javax.swing.JTextPane urlImageM;
    // End of variables declaration//GEN-END:variables
}
